import { LiveChannel } from '../types';

export const LIVE_CHANNELS: LiveChannel[] = [
  { name: 'ABC USA', embed: 'https://dlhd.dad/stream/stream-51.php', category: 'News', channelNumber: 1 },
  { name: 'AHC (American Heroes Channel)', embed: 'https://dlhd.dad/stream/stream-206.php', category: 'Documentary', channelNumber: 2 },
  { name: 'Antenna TV USA', embed: 'https://dlhd.dad/stream/stream-283.php', category: 'Entertainment', channelNumber: 3 },
  { name: 'A&E USA', embed: 'https://dlhd.dad/stream/stream-302.php', category: 'Entertainment', channelNumber: 4 },
  { name: 'AMC USA', embed: 'https://dlhd.dad/stream/stream-303.php', category: 'Entertainment', channelNumber: 5 },
  { name: 'Animal Planet', embed: 'https://dlhd.dad/stream/stream-304.php', category: 'Documentary', channelNumber: 6 },
  { name: 'Astro SuperSport 1', embed: 'https://dlhd.dad/stream/stream-123.php', category: 'Sports', channelNumber: 7 },
  { name: 'Astro SuperSport 2', embed: 'https://dlhd.dad/stream/stream-124.php', category: 'Sports', channelNumber: 8 },
  { name: 'Astro SuperSport 3', embed: 'https://dlhd.dad/stream/stream-125.php', category: 'Sports', channelNumber: 9 },
  { name: 'Astro SuperSport 4', embed: 'https://dlhd.dad/stream/stream-126.php', category: 'Sports', channelNumber: 10 },
  { name: 'Arena Sport 1 Premium', embed: 'https://dlhd.dad/stream/stream-134.php', category: 'Sports', channelNumber: 11 },
  { name: 'Arena Sport 2 Premium', embed: 'https://dlhd.dad/stream/stream-135.php', category: 'Sports', channelNumber: 12 },
  { name: 'Arena Sport 3 Premium', embed: 'https://dlhd.dad/stream/stream-139.php', category: 'Sports', channelNumber: 13 },
  { name: 'Arena Sport 1 Serbia', embed: 'https://dlhd.dad/stream/stream-429.php', category: 'Sports', channelNumber: 14 },
  { name: 'Arena Sport 2 Serbia', embed: 'https://dlhd.dad/stream/stream-430.php', category: 'Sports', channelNumber: 15 },
  { name: 'Arena Sport 3 Serbia', embed: 'https://dlhd.dad/stream/stream-431.php', category: 'Sports', channelNumber: 16 },
  { name: 'Arena Sport 4 Serbia', embed: 'https://dlhd.dad/stream/stream-581.php', category: 'Sports', channelNumber: 17 },
  { name: 'Arena Sport 1 Croatia', embed: 'https://dlhd.dad/stream/stream-432.php', category: 'Sports', channelNumber: 18 },
  { name: 'Arena Sport 2 Croatia', embed: 'https://dlhd.dad/stream/stream-433.php', category: 'Sports', channelNumber: 19 },
  { name: 'Arena Sport 3 Croatia', embed: 'https://dlhd.dad/stream/stream-434.php', category: 'Sports', channelNumber: 20 },
  { name: 'Arena Sport 4 Croatia', embed: 'https://dlhd.dad/stream/stream-580.php', category: 'Sports', channelNumber: 21 },
  { name: 'Alkass One', embed: 'https://dlhd.dad/stream/stream-781.php', category: 'Sports', channelNumber: 22 },
  { name: 'Alkass Two', embed: 'https://dlhd.dad/stream/stream-782.php', category: 'Sports', channelNumber: 23 },
  { name: 'Alkass Three', embed: 'https://dlhd.dad/stream/stream-783.php', category: 'Sports', channelNumber: 24 },
  { name: 'Alkass Four', embed: 'https://dlhd.dad/stream/stream-784.php', category: 'Sports', channelNumber: 25 },
  { name: 'Arena Sport 1 BiH', embed: 'https://dlhd.dad/stream/stream-579.php', category: 'Sports', channelNumber: 26 },
  { name: 'Abu Dhabi Sports 1 UAE', embed: 'https://dlhd.dad/stream/stream-600.php', category: 'Sports', channelNumber: 27 },
  { name: 'Abu Dhabi Sports 2 UAE', embed: 'https://dlhd.dad/stream/stream-601.php', category: 'Sports', channelNumber: 28 },
  { name: 'Abu Dhabi Sports 1 Premium', embed: 'https://dlhd.dad/stream/stream-609.php', category: 'Sports', channelNumber: 29 },
  { name: 'Abu Dhabi Sports 2 Premium', embed: 'https://dlhd.dad/stream/stream-610.php', category: 'Sports', channelNumber: 30 },
  { name: 'Astro Cricket', embed: 'https://dlhd.dad/stream/stream-370.php', category: 'Sports', channelNumber: 31 },
  { name: 'Antena 3 Spain', embed: 'https://dlhd.dad/stream/stream-531.php', category: 'Entertainment', channelNumber: 32 },
  { name: 'Arena Sports Tenis Serbia', embed: 'https://dlhd.dad/stream/stream-612.php', category: 'Sports', channelNumber: 33 },
  { name: 'ACC Network USA', embed: 'https://dlhd.dad/stream/stream-664.php', category: 'Sports', channelNumber: 34 },
  { name: 'Adult Swim', embed: 'https://dlhd.dad/stream/stream-295.php', category: 'Entertainment', channelNumber: 35 },
  { name: 'A Sport PK', embed: 'https://dlhd.dad/stream/stream-269.php', category: 'Sports', channelNumber: 36 },
  { name: 'AXN Movies Portugal', embed: 'https://dlhd.dad/stream/stream-717.php', category: 'Movies', channelNumber: 37 },
  { name: 'Arte DE', embed: 'https://dlhd.dad/stream/stream-725.php', category: 'Documentary', channelNumber: 38 },
  { name: 'AXS TV USA', embed: 'https://dlhd.dad/stream/stream-742.php', category: 'Entertainment', channelNumber: 39 },
  { name: 'ABC NY USA', embed: 'https://dlhd.dad/stream/stream-766.php', category: 'News', channelNumber: 40 },
  { name: 'Azteca 7 MX', embed: 'https://dlhd.dad/stream/stream-844.php', category: 'Entertainment', channelNumber: 41 },
  { name: 'Altitude Sports', embed: 'https://dlhd.dad/stream/stream-923.php', category: 'Sports', channelNumber: 42 },
  { name: 'Azteca Uno MX', embed: 'https://dlhd.dad/stream/stream-934.php', category: 'Entertainment', channelNumber: 43 },
  { name: 'Arena Sport 5 Serbia', embed: 'https://dlhd.dad/stream/stream-940.php', category: 'Sports', channelNumber: 44 },
  { name: 'Arena Sport 6 Serbia', embed: 'https://dlhd.dad/stream/stream-941.php', category: 'Sports', channelNumber: 45 },
  { name: 'Arena Sport 7 Serbia', embed: 'https://dlhd.dad/stream/stream-942.php', category: 'Sports', channelNumber: 46 },
  { name: 'Arena Sport 8 Serbia', embed: 'https://dlhd.dad/stream/stream-943.php', category: 'Sports', channelNumber: 47 },
  { name: 'Arena Sport 9 Serbia', embed: 'https://dlhd.dad/stream/stream-944.php', category: 'Sports', channelNumber: 48 },
  { name: 'Arena Sport 10 Serbia', embed: 'https://dlhd.dad/stream/stream-945.php', category: 'Sports', channelNumber: 49 },
  { name: 'Arte France', embed: 'https://dlhd.dad/stream/stream-958.php', category: 'Documentary', channelNumber: 50 },
  { name: 'Automoto La chaîne', embed: 'https://dlhd.dad/stream/stream-961.php', category: 'Lifestyle', channelNumber: 51 },
  { name: 'ATV Turkey', embed: 'https://dlhd.dad/stream/stream-1000.php', category: 'Entertainment', channelNumber: 52 },
  { name: 'A Spor Turkey', embed: 'https://dlhd.dad/stream/stream-1011.php', category: 'Sports', channelNumber: 53 },
  { name: 'beIN Sports MENA English 1', embed: 'https://dlhd.dad/stream/stream-61.php', category: 'Sports', channelNumber: 54 },
  { name: 'beIN Sports MENA English 2', embed: 'https://dlhd.dad/stream/stream-90.php', category: 'Sports', channelNumber: 55 },
  { name: 'beIN Sports 1 Arabic', embed: 'https://dlhd.dad/stream/stream-91.php', category: 'Sports', channelNumber: 56 },
  { name: 'beIN Sports 2 Arabic', embed: 'https://dlhd.dad/stream/stream-92.php', category: 'Sports', channelNumber: 57 },
  { name: 'beIN Sports 3 Arabic', embed: 'https://dlhd.dad/stream/stream-93.php', category: 'Sports', channelNumber: 58 },
  { name: 'beIN Sports 4 Arabic', embed: 'https://dlhd.dad/stream/stream-94.php', category: 'Sports', channelNumber: 59 },
  { name: 'beIN Sports 5 Arabic', embed: 'https://dlhd.dad/stream/stream-95.php', category: 'Sports', channelNumber: 60 },
  { name: 'beIN Sports 6 Arabic', embed: 'https://dlhd.dad/stream/stream-96.php', category: 'Sports', channelNumber: 61 },
  { name: 'beIN Sports 7 Arabic', embed: 'https://dlhd.dad/stream/stream-97.php', category: 'Sports', channelNumber: 62 },
  { name: 'beIN Sports 8 Arabic', embed: 'https://dlhd.dad/stream/stream-98.php', category: 'Sports', channelNumber: 63 },
  { name: 'beIN Sports 9 Arabic', embed: 'https://dlhd.dad/stream/stream-99.php', category: 'Sports', channelNumber: 64 },
  { name: 'beIN SPORTS XTRA 1', embed: 'https://dlhd.dad/stream/stream-100.php', category: 'Sports', channelNumber: 65 },
  { name: 'beIN Sports MAX 4 France', embed: 'https://dlhd.dad/stream/stream-494.php', category: 'Sports', channelNumber: 66 },
  { name: 'beIN Sports MAX 5 France', embed: 'https://dlhd.dad/stream/stream-495.php', category: 'Sports', channelNumber: 67 },
  { name: 'beIN Sports MAX 6 France', embed: 'https://dlhd.dad/stream/stream-496.php', category: 'Sports', channelNumber: 68 },
  { name: 'beIN Sports MAX 7 France', embed: 'https://dlhd.dad/stream/stream-497.php', category: 'Sports', channelNumber: 69 },
  { name: 'beIN Sports MAX 8 France', embed: 'https://dlhd.dad/stream/stream-498.php', category: 'Sports', channelNumber: 70 },
  { name: 'beIN Sports MAX 9 France', embed: 'https://dlhd.dad/stream/stream-499.php', category: 'Sports', channelNumber: 71 },
  { name: 'beIN Sports MAX 10 France', embed: 'https://dlhd.dad/stream/stream-500.php', category: 'Sports', channelNumber: 72 },
  { name: 'beIN SPORTS 1 France', embed: 'https://dlhd.dad/stream/stream-116.php', category: 'Sports', channelNumber: 73 },
  { name: 'beIN SPORTS 2 France', embed: 'https://dlhd.dad/stream/stream-117.php', category: 'Sports', channelNumber: 74 },
  { name: 'beIN SPORTS 3 France', embed: 'https://dlhd.dad/stream/stream-118.php', category: 'Sports', channelNumber: 75 },
  { name: 'beIN SPORTS 1 Turkey', embed: 'https://dlhd.dad/stream/stream-62.php', category: 'Sports', channelNumber: 76 },
  { name: 'beIN SPORTS 2 Turkey', embed: 'https://dlhd.dad/stream/stream-63.php', category: 'Sports', channelNumber: 77 },
  { name: 'beIN SPORTS 3 Turkey', embed: 'https://dlhd.dad/stream/stream-64.php', category: 'Sports', channelNumber: 78 },
  { name: 'beIN SPORTS 4 Turkey', embed: 'https://dlhd.dad/stream/stream-67.php', category: 'Sports', channelNumber: 79 },
  { name: 'BeIN Sports HD Qatar', embed: 'https://dlhd.dad/stream/stream-578.php', category: 'Sports', channelNumber: 80 },
  { name: 'BeIN SPORTS USA', embed: 'https://dlhd.dad/stream/stream-425.php', category: 'Sports', channelNumber: 81 },
  { name: 'beIN SPORTS en Español', embed: 'https://dlhd.dad/stream/stream-372.php', category: 'Sports', channelNumber: 82 },
  { name: 'beIN SPORTS Australia 1', embed: 'https://dlhd.dad/stream/stream-491.php', category: 'Sports', channelNumber: 83 },
  { name: 'beIN SPORTS Australia 2', embed: 'https://dlhd.dad/stream/stream-492.php', category: 'Sports', channelNumber: 84 },
  { name: 'beIN SPORTS Australia 3', embed: 'https://dlhd.dad/stream/stream-493.php', category: 'Sports', channelNumber: 85 },
  { name: 'Barca TV Spain', embed: 'https://dlhd.dad/stream/stream-522.php', category: 'Sports', channelNumber: 86 },
  { name: 'Benfica TV PT', embed: 'https://dlhd.dad/stream/stream-380.php', category: 'Sports', channelNumber: 87 },
  { name: 'Boomerang', embed: 'https://dlhd.dad/stream/stream-648.php', category: 'Kids', channelNumber: 88 },
  { name: 'BNT 1 Bulgaria', embed: 'https://dlhd.dad/stream/stream-476.php', category: 'Entertainment', channelNumber: 89 },
  { name: 'BNT 2 Bulgaria', embed: 'https://dlhd.dad/stream/stream-477.php', category: 'Entertainment', channelNumber: 90 },
  { name: 'BNT 3 Bulgaria', embed: 'https://dlhd.dad/stream/stream-478.php', category: 'Entertainment', channelNumber: 91 },
  { name: 'BR Fernsehen DE', embed: 'https://dlhd.dad/stream/stream-737.php', category: 'Entertainment', channelNumber: 92 },
  { name: 'bTV Bulgaria', embed: 'https://dlhd.dad/stream/stream-479.php', category: 'Entertainment', channelNumber: 93 },
  { name: 'bTV Action Bulgaria', embed: 'https://dlhd.dad/stream/stream-481.php', category: 'Entertainment', channelNumber: 94 },
  { name: 'bTV Lady Bulgaria', embed: 'https://dlhd.dad/stream/stream-484.php', category: 'Lifestyle', channelNumber: 95 },
  { name: 'BBC America (BBCA)', embed: 'https://dlhd.dad/stream/stream-305.php', category: 'Entertainment', channelNumber: 96 },
  { name: 'BET USA', embed: 'https://dlhd.dad/stream/stream-306.php', category: 'Entertainment', channelNumber: 97 },
  { name: 'Bravo USA', embed: 'https://dlhd.dad/stream/stream-307.php', category: 'Lifestyle', channelNumber: 98 },
  { name: 'BBC News Channel HD', embed: 'https://dlhd.dad/stream/stream-349.php', category: 'News', channelNumber: 99 },
  { name: 'BBC One UK', embed: 'https://dlhd.dad/stream/stream-356.php', category: 'Entertainment', channelNumber: 100 },
  { name: 'BBC Two UK', embed: 'https://dlhd.dad/stream/stream-357.php', category: 'Entertainment', channelNumber: 101 },
  { name: 'BBC Three UK', embed: 'https://dlhd.dad/stream/stream-358.php', category: 'Entertainment', channelNumber: 102 },
  { name: 'BBC Four UK', embed: 'https://dlhd.dad/stream/stream-359.php', category: 'Entertainment', channelNumber: 103 },
  { name: 'BIG TEN Network (BTN USA)', embed: 'https://dlhd.dad/stream/stream-397.php', category: 'Sports', channelNumber: 104 },
  { name: 'beIN Sports 1 Malaysia', embed: 'https://dlhd.dad/stream/stream-712.php', category: 'Sports', channelNumber: 105 },
  { name: 'beIN Sports 2 Malaysia', embed: 'https://dlhd.dad/stream/stream-713.php', category: 'Sports', channelNumber: 106 },
  { name: 'beIN Sports 3 Malaysia', embed: 'https://dlhd.dad/stream/stream-714.php', category: 'Sports', channelNumber: 107 },
  { name: 'BFM TV France', embed: 'https://dlhd.dad/stream/stream-957.php', category: 'News', channelNumber: 108 },
  { name: 'bein Sports 5 Turkey', embed: 'https://dlhd.dad/stream/stream-1010.php', category: 'Sports', channelNumber: 109 },
  { name: 'Bandsports Brasil', embed: 'https://dlhd.dad/stream/stream-275.php', category: 'Sports', channelNumber: 110 },
  { name: 'Canal+ MotoGP France', embed: 'https://dlhd.dad/stream/stream-271.php', category: 'Sports', channelNumber: 111 },
  { name: 'Canal+ Formula 1', embed: 'https://dlhd.dad/stream/stream-273.php', category: 'Sports', channelNumber: 112 },
  { name: 'CW PIX 11 USA', embed: 'https://dlhd.dad/stream/stream-280.php', category: 'Entertainment', channelNumber: 113 },
  { name: 'CBS USA', embed: 'https://dlhd.dad/stream/stream-52.php', category: 'Entertainment', channelNumber: 114 },
  { name: 'Court TV USA', embed: 'https://dlhd.dad/stream/stream-281.php', category: 'Entertainment', channelNumber: 115 },
  { name: 'CW USA', embed: 'https://dlhd.dad/stream/stream-300.php', category: 'Entertainment', channelNumber: 116 },
  { name: 'CNBC USA', embed: 'https://dlhd.dad/stream/stream-309.php', category: 'News', channelNumber: 117 },
  { name: 'Comedy Central', embed: 'https://dlhd.dad/stream/stream-310.php', category: 'Entertainment', channelNumber: 118 },
  { name: 'Cartoon Network', embed: 'https://dlhd.dad/stream/stream-339.php', category: 'Kids', channelNumber: 119 },
  { name: 'CNN USA', embed: 'https://dlhd.dad/stream/stream-345.php', category: 'News', channelNumber: 120 },
  { name: 'Cinemax USA', embed: 'https://dlhd.dad/stream/stream-374.php', category: 'Movies', channelNumber: 121 },
  { name: 'Cuatro Spain', embed: 'https://dlhd.dad/stream/stream-535.php', category: 'Entertainment', channelNumber: 122 },
  { name: 'Channel 4 UK', embed: 'https://dlhd.dad/stream/stream-354.php', category: 'Entertainment', channelNumber: 123 },
  { name: 'Channel 5 UK', embed: 'https://dlhd.dad/stream/stream-355.php', category: 'Entertainment', channelNumber: 124 },
  { name: 'CBS Sports Network (CBSSN)', embed: 'https://dlhd.dad/stream/stream-308.php', category: 'Sports', channelNumber: 125 },
  { name: 'Canal+ France', embed: 'https://dlhd.dad/stream/stream-121.php', category: 'Entertainment', channelNumber: 126 },
  { name: 'Canal+ Sport France', embed: 'https://dlhd.dad/stream/stream-122.php', category: 'Sports', channelNumber: 127 },
  { name: 'Canal+ Foot France', embed: 'https://dlhd.dad/stream/stream-463.php', category: 'Sports', channelNumber: 128 },
  { name: 'Canal+ Sport360', embed: 'https://dlhd.dad/stream/stream-464.php', category: 'Sports', channelNumber: 129 },
  { name: 'Canal 11 Portugal', embed: 'https://dlhd.dad/stream/stream-540.php', category: 'Sports', channelNumber: 130 },
  { name: 'Canal+ Sport Poland', embed: 'https://dlhd.dad/stream/stream-48.php', category: 'Sports', channelNumber: 131 },
  { name: 'Canal+ Sport 2 Poland', embed: 'https://dlhd.dad/stream/stream-73.php', category: 'Sports', channelNumber: 132 },
  { name: 'Canal+ Sport 3 Poland', embed: 'https://dlhd.dad/stream/stream-259.php', category: 'Sports', channelNumber: 133 },
  { name: 'Canal+ Sport 5 Poland', embed: 'https://dlhd.dad/stream/stream-75.php', category: 'Sports', channelNumber: 134 },
  { name: 'Canal+ Premium Poland', embed: 'https://dlhd.dad/stream/stream-566.php', category: 'Entertainment', channelNumber: 135 },
  { name: 'Canal+ Family Poland', embed: 'https://dlhd.dad/stream/stream-567.php', category: 'Kids', channelNumber: 136 },
  { name: 'Canal+ Seriale Poland', embed: 'https://dlhd.dad/stream/stream-570.php', category: 'Movies', channelNumber: 137 },
  { name: 'Canal+ Sport 1 Afrique', embed: 'https://dlhd.dad/stream/stream-486.php', category: 'Sports', channelNumber: 138 },
  { name: 'Canal+ Sport 2 Afrique', embed: 'https://dlhd.dad/stream/stream-487.php', category: 'Sports', channelNumber: 139 },
  { name: 'Canal+ Sport 3 Afrique', embed: 'https://dlhd.dad/stream/stream-488.php', category: 'Sports', channelNumber: 140 },
  { name: 'Canal+ Sport 4 Afrique', embed: 'https://dlhd.dad/stream/stream-489.php', category: 'Sports', channelNumber: 141 },
  { name: 'Canal+ Sport 5 Afrique', embed: 'https://dlhd.dad/stream/stream-490.php', category: 'Sports', channelNumber: 142 },
  { name: 'CANAL 9 Denmark', embed: 'https://dlhd.dad/stream/stream-805.php', category: 'Sports', channelNumber: 143 },
  { name: 'Combate Brasil', embed: 'https://dlhd.dad/stream/stream-89.php', category: 'Sports', channelNumber: 144 },
  { name: 'Cosmote Sport 1 HD', embed: 'https://dlhd.dad/stream/stream-622.php', category: 'Sports', channelNumber: 145 },
  { name: 'Cosmote Sport 2 HD', embed: 'https://dlhd.dad/stream/stream-623.php', category: 'Sports', channelNumber: 146 },
  { name: 'Cosmote Sport 3 HD', embed: 'https://dlhd.dad/stream/stream-624.php', category: 'Sports', channelNumber: 147 },
  { name: 'Cosmote Sport 4 HD', embed: 'https://dlhd.dad/stream/stream-625.php', category: 'Sports', channelNumber: 148 },
  { name: 'Cosmote Sport 5 HD', embed: 'https://dlhd.dad/stream/stream-626.php', category: 'Sports', channelNumber: 149 },
  { name: 'Cosmote Sport 6 HD', embed: 'https://dlhd.dad/stream/stream-627.php', category: 'Sports', channelNumber: 150 },
  { name: 'Cosmote Sport 7 HD', embed: 'https://dlhd.dad/stream/stream-628.php', category: 'Sports', channelNumber: 151 },
  { name: 'Cosmote Sport 8 HD', embed: 'https://dlhd.dad/stream/stream-629.php', category: 'Sports', channelNumber: 152 },
  { name: 'Cosmote Sport 9 HD', embed: 'https://dlhd.dad/stream/stream-630.php', category: 'Sports', channelNumber: 153 },
  { name: 'Channel 9 Israel', embed: 'https://dlhd.dad/stream/stream-546.php', category: 'Entertainment', channelNumber: 154 },
  { name: 'Channel 10 Israel', embed: 'https://dlhd.dad/stream/stream-547.php', category: 'Entertainment', channelNumber: 155 },
  { name: 'Channel 11 Israel', embed: 'https://dlhd.dad/stream/stream-548.php', category: 'Entertainment', channelNumber: 156 },
  { name: 'Channel 12 Israel', embed: 'https://dlhd.dad/stream/stream-549.php', category: 'Entertainment', channelNumber: 157 },
  { name: 'Channel 13 Israel', embed: 'https://dlhd.dad/stream/stream-551.php', category: 'Entertainment', channelNumber: 158 },
  { name: 'Channel 14 Israel', embed: 'https://dlhd.dad/stream/stream-552.php', category: 'Entertainment', channelNumber: 159 },
  { name: 'C More First Sweden', embed: 'https://dlhd.dad/stream/stream-812.php', category: 'Movies', channelNumber: 160 },
  { name: 'C More Hits Sweden', embed: 'https://dlhd.dad/stream/stream-813.php', category: 'Movies', channelNumber: 161 },
  { name: 'C More Series Sweden', embed: 'https://dlhd.dad/stream/stream-814.php', category: 'Movies', channelNumber: 162 },
  { name: 'COZI TV USA', embed: 'https://dlhd.dad/stream/stream-748.php', category: 'Entertainment', channelNumber: 163 },
  { name: 'CMT USA', embed: 'https://dlhd.dad/stream/stream-647.php', category: 'Lifestyle', channelNumber: 164 },
  { name: 'CTV Canada', embed: 'https://dlhd.dad/stream/stream-602.php', category: 'Entertainment', channelNumber: 165 },
  { name: 'CTV 2 Canada', embed: 'https://dlhd.dad/stream/stream-838.php', category: 'Entertainment', channelNumber: 166 },
  { name: 'Crime+ Investigation USA', embed: 'https://dlhd.dad/stream/stream-669.php', category: 'Documentary', channelNumber: 167 },
  { name: 'Comet USA', embed: 'https://dlhd.dad/stream/stream-696.php', category: 'Entertainment', channelNumber: 168 },
  { name: 'Cooking Channel USA', embed: 'https://dlhd.dad/stream/stream-697.php', category: 'Lifestyle', channelNumber: 169 },
  { name: 'Cleo TV', embed: 'https://dlhd.dad/stream/stream-715.php', category: 'Entertainment', channelNumber: 170 },
  { name: 'C SPAN 1', embed: 'https://dlhd.dad/stream/stream-750.php', category: 'News', channelNumber: 171 },
  { name: 'CBSNY USA', embed: 'https://dlhd.dad/stream/stream-767.php', category: 'News', channelNumber: 172 },
  { name: 'Chicago Sports Network', embed: 'https://dlhd.dad/stream/stream-776.php', category: 'Sports', channelNumber: 173 },
  { name: 'Citytv', embed: 'https://dlhd.dad/stream/stream-831.php', category: 'Entertainment', channelNumber: 174 },
  { name: 'CBC CA', embed: 'https://dlhd.dad/stream/stream-832.php', category: 'Entertainment', channelNumber: 175 },
  { name: 'Claro Sports MX', embed: 'https://dlhd.dad/stream/stream-933.php', category: 'Sports', channelNumber: 176 },
  { name: 'Canal5 MX', embed: 'https://dlhd.dad/stream/stream-936.php', category: 'Entertainment', channelNumber: 177 },
  { name: 'C8 France', embed: 'https://dlhd.dad/stream/stream-956.php', category: 'Entertainment', channelNumber: 178 },
  { name: 'CNews France', embed: 'https://dlhd.dad/stream/stream-964.php', category: 'News', channelNumber: 179 },
  { name: 'Canal+ Sport CZ', embed: 'https://dlhd.dad/stream/stream-1020.php', category: 'Sports', channelNumber: 180 },
  { name: 'CT Sport CZ', embed: 'https://dlhd.dad/stream/stream-1033.php', category: 'Sports', channelNumber: 181 },
  { name: 'Nova HD CZ', embed: 'https://dlhd.dad/stream/stream-1034.php', category: 'Entertainment', channelNumber: 182 },
  { name: 'CT1 HD CZ', embed: 'https://dlhd.dad/stream/stream-1035.php', category: 'Entertainment', channelNumber: 183 },
  { name: 'CT2 HD CZ', embed: 'https://dlhd.dad/stream/stream-1036.php', category: 'Entertainment', channelNumber: 184 },
  { name: 'TN Live CZ', embed: 'https://dlhd.dad/stream/stream-1037.php', category: 'News', channelNumber: 185 },
  { name: 'OnePlay Sport 4 CZ', embed: 'https://dlhd.dad/stream/stream-1038.php', category: 'Sports', channelNumber: 186 },
  { name: 'OnePlay MD2 CZ', embed: 'https://dlhd.dad/stream/stream-1039.php', category: 'Sports', channelNumber: 187 },
  { name: 'OnePlay MD3 CZ', embed: 'https://dlhd.dad/stream/stream-1040.php', category: 'Sports', channelNumber: 188 },
  { name: 'OnePlay MD4 CZ', embed: 'https://dlhd.dad/stream/stream-1041.php', category: 'Sports', channelNumber: 189 },
  { name: 'Sport 1 CZ', embed: 'https://dlhd.dad/stream/stream-1042.php', category: 'Sports', channelNumber: 190 },
  { name: 'Canal+ Sport 2 CZ', embed: 'https://dlhd.dad/stream/stream-1043.php', category: 'Sports', channelNumber: 191 },
  { name: 'Canal+ Sport 3 CZ', embed: 'https://dlhd.dad/stream/stream-1044.php', category: 'Sports', channelNumber: 192 },
  { name: 'Canal+ Sport 4 CZ', embed: 'https://dlhd.dad/stream/stream-1045.php', category: 'Sports', channelNumber: 193 },
  { name: 'Canal+ Sport 5 CZ', embed: 'https://dlhd.dad/stream/stream-1046.php', category: 'Sports', channelNumber: 194 },
  { name: 'Canal+ Sport 6 CZ', embed: 'https://dlhd.dad/stream/stream-1047.php', category: 'Sports', channelNumber: 195 },
  { name: 'Canal+ Sport 7 CZ', embed: 'https://dlhd.dad/stream/stream-1048.php', category: 'Sports', channelNumber: 196 },
  { name: 'Canal+ Sport 8 CZ', embed: 'https://dlhd.dad/stream/stream-1049.php', category: 'Sports', channelNumber: 197 },
  { name: 'JOJ SK', embed: 'https://dlhd.dad/stream/stream-1050.php', category: 'Entertainment', channelNumber: 198 },
  { name: 'Dajto SK', embed: 'https://dlhd.dad/stream/stream-1051.php', category: 'Entertainment', channelNumber: 199 },
  { name: 'JOJ Šport SK', embed: 'https://dlhd.dad/stream/stream-1052.php', category: 'Sports', channelNumber: 200 },
  { name: 'Voyo Special 1 SK', embed: 'https://dlhd.dad/stream/stream-1053.php', category: 'Entertainment', channelNumber: 201 },
  { name: 'Voyo Special 2 SK', embed: 'https://dlhd.dad/stream/stream-1054.php', category: 'Entertainment', channelNumber: 202 },
  { name: 'Voyo Special 3 SK', embed: 'https://dlhd.dad/stream/stream-1055.php', category: 'Entertainment', channelNumber: 203 },
  { name: 'Voyo Special 4 SK', embed: 'https://dlhd.dad/stream/stream-1056.php', category: 'Entertainment', channelNumber: 204 },
  { name: 'Voyo Special 7 SK', embed: 'https://dlhd.dad/stream/stream-1057.php', category: 'Entertainment', channelNumber: 205 },
  { name: 'Voyo Special 8 SK', embed: 'https://dlhd.dad/stream/stream-1058.php', category: 'Entertainment', channelNumber: 206 },
  { name: 'Voyo Special 9 SK', embed: 'https://dlhd.dad/stream/stream-1059.php', category: 'Entertainment', channelNumber: 207 },
  { name: 'Nova Sport 3 SK', embed: 'https://dlhd.dad/stream/stream-1060.php', category: 'Sports', channelNumber: 208 },
  { name: 'Nova Sport 4 SK', embed: 'https://dlhd.dad/stream/stream-1061.php', category: 'Sports', channelNumber: 209 },
  { name: 'Nova Sport 5 SK', embed: 'https://dlhd.dad/stream/stream-1062.php', category: 'Sports', channelNumber: 210 },
  { name: 'Canal+ Sport SK', embed: 'https://dlhd.dad/stream/stream-1063.php', category: 'Sports', channelNumber: 211 },
  { name: 'Canal+ Sport 2 SK', embed: 'https://dlhd.dad/stream/stream-1064.php', category: 'Sports', channelNumber: 212 },
  { name: 'Canal+ Sport 3 SK', embed: 'https://dlhd.dad/stream/stream-1065.php', category: 'Sports', channelNumber: 213 },
  { name: 'Canal+ Sport 4 SK', embed: 'https://dlhd.dad/stream/stream-1066.php', category: 'Sports', channelNumber: 214 },
  { name: 'CBS Sports Golazo', embed: 'https://dlhd.dad/stream/stream-910.php', category: 'Sports', channelNumber: 215 },
  { name: 'CMTV Portugal', embed: 'https://dlhd.dad/stream/stream-790.php', category: 'News', channelNumber: 216 },
  { name: 'Cytavision Sports 1 Cyprus', embed: 'https://dlhd.dad/stream/stream-911.php', category: 'Sports', channelNumber: 217 },
  { name: 'Cytavision Sports 2 Cyprus', embed: 'https://dlhd.dad/stream/stream-912.php', category: 'Sports', channelNumber: 218 },
  { name: 'Cytavision Sports 3 Cyprus', embed: 'https://dlhd.dad/stream/stream-913.php', category: 'Sports', channelNumber: 219 },
  { name: 'Cytavision Sports 4 Cyprus', embed: 'https://dlhd.dad/stream/stream-914.php', category: 'Sports', channelNumber: 220 },
  { name: 'Cytavision Sports 5 Cyprus', embed: 'https://dlhd.dad/stream/stream-915.php', category: 'Sports', channelNumber: 221 },
  { name: 'Cytavision Sports 6 Cyprus', embed: 'https://dlhd.dad/stream/stream-916.php', category: 'Sports', channelNumber: 222 },
  { name: 'Cytavision Sports 7 Cyprus', embed: 'https://dlhd.dad/stream/stream-917.php', category: 'Sports', channelNumber: 223 },
  { name: 'DAZN 1 UK', embed: 'https://dlhd.dad/stream/stream-230.php', category: 'Sports', channelNumber: 224 },
  { name: 'Discovery Velocity CA', embed: 'https://dlhd.dad/stream/stream-285.php', category: 'Lifestyle', channelNumber: 225 },
  { name: 'DAZN 1 Bar DE', embed: 'https://dlhd.dad/stream/stream-426.php', category: 'Sports', channelNumber: 226 },
  { name: 'DAZN 2 Bar DE', embed: 'https://dlhd.dad/stream/stream-427.php', category: 'Sports', channelNumber: 227 },
  { name: 'DAZN 1 Spain', embed: 'https://dlhd.dad/stream/stream-445.php', category: 'Sports', channelNumber: 228 },
  { name: 'DAZN 2 Spain', embed: 'https://dlhd.dad/stream/stream-446.php', category: 'Sports', channelNumber: 229 },
  { name: 'DAZN 3 Spain', embed: 'https://dlhd.dad/stream/stream-447.php', category: 'Sports', channelNumber: 230 },
  { name: 'DAZN 4 Spain', embed: 'https://dlhd.dad/stream/stream-448.php', category: 'Sports', channelNumber: 231 },
  { name: 'DAZN F1 ES', embed: 'https://dlhd.dad/stream/stream-537.php', category: 'Sports', channelNumber: 232 },
  { name: 'DAZN LaLiga', embed: 'https://dlhd.dad/stream/stream-538.php', category: 'Sports', channelNumber: 233 },
  { name: 'DAZN Portugal FIFA Mundial de Clubes', embed: 'https://dlhd.dad/stream/stream-918.php', category: 'Sports', channelNumber: 234 },
  { name: 'DR1 Denmark', embed: 'https://dlhd.dad/stream/stream-801.php', category: 'Entertainment', channelNumber: 235 },
  { name: 'DR2 Denmark', embed: 'https://dlhd.dad/stream/stream-802.php', category: 'Entertainment', channelNumber: 236 },
  { name: 'DAZN Ligue 1 France', embed: 'https://dlhd.dad/stream/stream-960.php', category: 'Sports', channelNumber: 237 },
  { name: 'Digi Sport 1 Romania', embed: 'https://dlhd.dad/stream/stream-400.php', category: 'Sports', channelNumber: 238 },
  { name: 'Digi Sport 2 Romania', embed: 'https://dlhd.dad/stream/stream-401.php', category: 'Sports', channelNumber: 239 },
  { name: 'Digi Sport 3 Romania', embed: 'https://dlhd.dad/stream/stream-402.php', category: 'Sports', channelNumber: 240 },
  { name: 'Digi Sport 4 Romania', embed: 'https://dlhd.dad/stream/stream-403.php', category: 'Sports', channelNumber: 241 },
  { name: 'Diema Sport Bulgaria', embed: 'https://dlhd.dad/stream/stream-465.php', category: 'Sports', channelNumber: 242 },
  { name: 'Diema Sport 2 Bulgaria', embed: 'https://dlhd.dad/stream/stream-466.php', category: 'Sports', channelNumber: 243 },
  { name: 'Diema Sport 3 Bulgaria', embed: 'https://dlhd.dad/stream/stream-467.php', category: 'Sports', channelNumber: 244 },
  { name: 'Diema Bulgaria', embed: 'https://dlhd.dad/stream/stream-482.php', category: 'Entertainment', channelNumber: 245 },
  { name: 'Diema Family Bulgaria', embed: 'https://dlhd.dad/stream/stream-485.php', category: 'Entertainment', channelNumber: 246 },
  { name: 'Dubai Sports 1 UAE', embed: 'https://dlhd.dad/stream/stream-604.php', category: 'Sports', channelNumber: 247 },
  { name: 'Dubai Sports 2 UAE', embed: 'https://dlhd.dad/stream/stream-605.php', category: 'Sports', channelNumber: 248 },
  { name: 'Dubai Sports 3 UAE', embed: 'https://dlhd.dad/stream/stream-606.php', category: 'Sports', channelNumber: 249 },
  { name: 'Dubai Racing 2 UAE', embed: 'https://dlhd.dad/stream/stream-608.php', category: 'Sports', channelNumber: 250 },
  { name: 'DSTV Mzansi Magic', embed: 'https://dlhd.dad/stream/stream-786.php', category: 'Entertainment', channelNumber: 251 },
  { name: 'DSTV M-Net', embed: 'https://dlhd.dad/stream/stream-827.php', category: 'Entertainment', channelNumber: 252 },
  { name: 'DSTV kykNET & kie', embed: 'https://dlhd.dad/stream/stream-828.php', category: 'Entertainment', channelNumber: 253 },
  { name: 'DAZN ZONA Italy', embed: 'https://dlhd.dad/stream/stream-877.php', category: 'Sports', channelNumber: 254 },
  { name: 'Discovery Life Channel', embed: 'https://dlhd.dad/stream/stream-311.php', category: 'Lifestyle', channelNumber: 255 },
  { name: 'Disney Channel', embed: 'https://dlhd.dad/stream/stream-312.php', category: 'Kids', channelNumber: 256 },
  { name: 'Discovery Channel', embed: 'https://dlhd.dad/stream/stream-313.php', category: 'Documentary', channelNumber: 257 },
  { name: 'Discovery Family', embed: 'https://dlhd.dad/stream/stream-657.php', category: 'Kids', channelNumber: 258 },
  { name: 'Disney XD', embed: 'https://dlhd.dad/stream/stream-314.php', category: 'Kids', channelNumber: 259 },
  { name: 'Destination America', embed: 'https://dlhd.dad/stream/stream-651.php', category: 'Documentary', channelNumber: 260 },
  { name: 'Disney JR', embed: 'https://dlhd.dad/stream/stream-652.php', category: 'Kids', channelNumber: 261 },
  { name: 'Dave', embed: 'https://dlhd.dad/stream/stream-348.php', category: 'Entertainment', channelNumber: 262 },
  { name: 'ESPN USA', embed: 'https://dlhd.dad/stream/stream-44.php', category: 'Sports', channelNumber: 263 },
  { name: 'ESPN2 USA', embed: 'https://dlhd.dad/stream/stream-45.php', category: 'Sports', channelNumber: 264 },
  { name: 'ESPNU USA', embed: 'https://dlhd.dad/stream/stream-316.php', category: 'Sports', channelNumber: 265 },
  { name: 'ESPN 1 NL', embed: 'https://dlhd.dad/stream/stream-379.php', category: 'Sports', channelNumber: 266 },
  { name: 'ESPN 2 NL', embed: 'https://dlhd.dad/stream/stream-386.php', category: 'Sports', channelNumber: 267 },
  { name: 'Eleven Sports 1 Poland', embed: 'https://dlhd.dad/stream/stream-71.php', category: 'Sports', channelNumber: 268 },
  { name: 'Eleven Sports 2 Poland', embed: 'https://dlhd.dad/stream/stream-72.php', category: 'Sports', channelNumber: 269 },
  { name: 'Eleven Sports 3 Poland', embed: 'https://dlhd.dad/stream/stream-428.php', category: 'Sports', channelNumber: 270 },
  { name: 'Eleven Sports 1 Portugal', embed: 'https://dlhd.dad/stream/stream-455.php', category: 'Sports', channelNumber: 271 },
  { name: 'Eleven Sports 2 Portugal', embed: 'https://dlhd.dad/stream/stream-456.php', category: 'Sports', channelNumber: 272 },
  { name: 'Eleven Sports 3 Portugal', embed: 'https://dlhd.dad/stream/stream-457.php', category: 'Sports', channelNumber: 273 },
  { name: 'Eleven Sports 4 Portugal', embed: 'https://dlhd.dad/stream/stream-458.php', category: 'Sports', channelNumber: 274 },
  { name: 'Eleven Sports 5 Portugal', embed: 'https://dlhd.dad/stream/stream-459.php', category: 'Sports', channelNumber: 275 },
  { name: 'EuroSport 1 Greece', embed: 'https://dlhd.dad/stream/stream-41.php', category: 'Sports', channelNumber: 276 },
  { name: 'EuroSport 2 Greece', embed: 'https://dlhd.dad/stream/stream-42.php', category: 'Sports', channelNumber: 277 },
  { name: 'EuroSport 1 Poland', embed: 'https://dlhd.dad/stream/stream-57.php', category: 'Sports', channelNumber: 278 },
  { name: 'EuroSport 2 Poland', embed: 'https://dlhd.dad/stream/stream-58.php', category: 'Sports', channelNumber: 279 },
  { name: 'Eurosport 1 SW', embed: 'https://dlhd.dad/stream/stream-231.php', category: 'Sports', channelNumber: 280 },
  { name: 'Eurosport 2 SW', embed: 'https://dlhd.dad/stream/stream-232.php', category: 'Sports', channelNumber: 281 },
  { name: 'Eurosport 1 NL', embed: 'https://dlhd.dad/stream/stream-233.php', category: 'Sports', channelNumber: 282 },
  { name: 'Eurosport 2 NL', embed: 'https://dlhd.dad/stream/stream-234.php', category: 'Sports', channelNumber: 283 },
  { name: 'EuroSport 1 Spain', embed: 'https://dlhd.dad/stream/stream-524.php', category: 'Sports', channelNumber: 284 },
  { name: 'EuroSport 2 Spain', embed: 'https://dlhd.dad/stream/stream-525.php', category: 'Sports', channelNumber: 285 },
  { name: 'EuroSport 1 Italy', embed: 'https://dlhd.dad/stream/stream-878.php', category: 'Sports', channelNumber: 286 },
  { name: 'EuroSport 2 Italy', embed: 'https://dlhd.dad/stream/stream-879.php', category: 'Sports', channelNumber: 287 },
  { name: 'ESPN Premium Argentina', embed: 'https://dlhd.dad/stream/stream-387.php', category: 'Sports', channelNumber: 288 },
  { name: 'ESPN Brasil', embed: 'https://dlhd.dad/stream/stream-81.php', category: 'Sports', channelNumber: 289 },
  { name: 'ESPN2 Brasil', embed: 'https://dlhd.dad/stream/stream-82.php', category: 'Sports', channelNumber: 290 },
  { name: 'ESPN3 Brasil', embed: 'https://dlhd.dad/stream/stream-83.php', category: 'Sports', channelNumber: 291 },
  { name: 'ESPN4 Brasil', embed: 'https://dlhd.dad/stream/stream-85.php', category: 'Sports', channelNumber: 292 },
  { name: 'ESPN Argentina', embed: 'https://dlhd.dad/stream/stream-149.php', category: 'Sports', channelNumber: 293 },
  { name: 'ESPN2 Argentina', embed: 'https://dlhd.dad/stream/stream-150.php', category: 'Sports', channelNumber: 294 },
  { name: 'ESPN Deportes', embed: 'https://dlhd.dad/stream/stream-375.php', category: 'Sports', channelNumber: 295 },
  { name: 'ESPNews', embed: 'https://dlhd.dad/stream/stream-288.php', category: 'Sports', channelNumber: 296 },
  { name: 'E! Entertainment Television', embed: 'https://dlhd.dad/stream/stream-315.php', category: 'Lifestyle', channelNumber: 297 },
  { name: 'E4 Channel', embed: 'https://dlhd.dad/stream/stream-363.php', category: 'Entertainment', channelNumber: 298 },
  { name: 'ESPN 3 NL', embed: 'https://dlhd.dad/stream/stream-888.php', category: 'Sports', channelNumber: 299 },
  { name: 'ERT 1 Greece', embed: 'https://dlhd.dad/stream/stream-774.php', category: 'Entertainment', channelNumber: 300 },
  { name: 'Eurosport 1 France', embed: 'https://dlhd.dad/stream/stream-772.php', category: 'Sports', channelNumber: 301 },
  { name: 'Eurosport 2 France', embed: 'https://dlhd.dad/stream/stream-773.php', category: 'Sports', channelNumber: 302 },
  { name: 'ESPN3 Argentina', embed: 'https://dlhd.dad/stream/stream-798.php', category: 'Sports', channelNumber: 303 },
  { name: 'ESPN 1 MX', embed: 'https://dlhd.dad/stream/stream-925.php', category: 'Sports', channelNumber: 304 },
  { name: 'ESPN 2 MX', embed: 'https://dlhd.dad/stream/stream-926.php', category: 'Sports', channelNumber: 305 },
  { name: 'ESPN 3 MX', embed: 'https://dlhd.dad/stream/stream-927.php', category: 'Sports', channelNumber: 306 },
  { name: 'ESPN 4 MX', embed: 'https://dlhd.dad/stream/stream-928.php', category: 'Sports', channelNumber: 307 },
  { name: 'FUSE TV USA', embed: 'https://dlhd.dad/stream/stream-279.php', category: 'Entertainment', channelNumber: 308 },
  { name: 'Fox Sports 1 USA', embed: 'https://dlhd.dad/stream/stream-39.php', category: 'Sports', channelNumber: 309 },
  { name: 'Fox Sports 2 USA', embed: 'https://dlhd.dad/stream/stream-758.php', category: 'Sports', channelNumber: 310 },
  { name: 'FOX Soccer Plus', embed: 'https://dlhd.dad/stream/stream-756.php', category: 'Sports', channelNumber: 311 },
  { name: 'Fox Cricket', embed: 'https://dlhd.dad/stream/stream-369.php', category: 'Sports', channelNumber: 312 },
  { name: 'FOX Deportes USA', embed: 'https://dlhd.dad/stream/stream-643.php', category: 'Sports', channelNumber: 313 },
  { name: 'FOX Sports 502 AU', embed: 'https://dlhd.dad/stream/stream-820.php', category: 'Sports', channelNumber: 314 },
  { name: 'FOX Sports 503 AU', embed: 'https://dlhd.dad/stream/stream-821.php', category: 'Sports', channelNumber: 315 },
  { name: 'FOX Sports 504 AU', embed: 'https://dlhd.dad/stream/stream-822.php', category: 'Sports', channelNumber: 316 },
  { name: 'FOX Sports 505 AU', embed: 'https://dlhd.dad/stream/stream-823.php', category: 'Sports', channelNumber: 317 },
  { name: 'FOX Sports 506 AU', embed: 'https://dlhd.dad/stream/stream-824.php', category: 'Sports', channelNumber: 318 },
  { name: 'FOX Sports 507 AU', embed: 'https://dlhd.dad/stream/stream-825.php', category: 'Sports', channelNumber: 319 },
  { name: 'Fox Sports 1 MX', embed: 'https://dlhd.dad/stream/stream-929.php', category: 'Sports', channelNumber: 320 },
  { name: 'Fox Sports 2 MX', embed: 'https://dlhd.dad/stream/stream-930.php', category: 'Sports', channelNumber: 321 },
  { name: 'Fox Sports 3 MX', embed: 'https://dlhd.dad/stream/stream-931.php', category: 'Sports', channelNumber: 322 },
  { name: 'Fox Sports Argentina', embed: 'https://dlhd.dad/stream/stream-787.php', category: 'Sports', channelNumber: 323 },
  { name: 'Fox Sports 2 Argentina', embed: 'https://dlhd.dad/stream/stream-788.php', category: 'Sports', channelNumber: 324 },
  { name: 'Fox Sports 3 Argentina', embed: 'https://dlhd.dad/stream/stream-789.php', category: 'Sports', channelNumber: 325 },
  { name: 'Fox Sports Premium MX', embed: 'https://dlhd.dad/stream/stream-830.php', category: 'Sports', channelNumber: 326 },
  { name: 'FilmBox Premium Poland', embed: 'https://dlhd.dad/stream/stream-568.php', category: 'Movies', channelNumber: 327 },
  { name: 'Fight Network', embed: 'https://dlhd.dad/stream/stream-757.php', category: 'Sports', channelNumber: 328 },
  { name: 'Fox Business', embed: 'https://dlhd.dad/stream/stream-297.php', category: 'News', channelNumber: 329 },
  { name: 'FOX HD Bulgaria', embed: 'https://dlhd.dad/stream/stream-483.php', category: 'Entertainment', channelNumber: 330 },
  { name: 'FOX USA', embed: 'https://dlhd.dad/stream/stream-54.php', category: 'Entertainment', channelNumber: 331 },
  { name: 'FX USA', embed: 'https://dlhd.dad/stream/stream-317.php', category: 'Entertainment', channelNumber: 332 },
  { name: 'FXX USA', embed: 'https://dlhd.dad/stream/stream-298.php', category: 'Entertainment', channelNumber: 333 },
  { name: 'Freeform', embed: 'https://dlhd.dad/stream/stream-301.php', category: 'Entertainment', channelNumber: 334 },
  { name: 'Fox News', embed: 'https://dlhd.dad/stream/stream-347.php', category: 'News', channelNumber: 335 },
  { name: 'FX Movie Channel', embed: 'https://dlhd.dad/stream/stream-381.php', category: 'Movies', channelNumber: 336 },
  { name: 'FYI', embed: 'https://dlhd.dad/stream/stream-665.php', category: 'Documentary', channelNumber: 337 },
  { name: 'Film4 UK', embed: 'https://dlhd.dad/stream/stream-688.php', category: 'Movies', channelNumber: 338 },
  { name: 'Fashion TV', embed: 'https://dlhd.dad/stream/stream-744.php', category: 'Lifestyle', channelNumber: 339 },
  { name: 'FETV - Family Entertainment Television', embed: 'https://dlhd.dad/stream/stream-751.php', category: 'Entertainment', channelNumber: 340 },
  { name: 'FOXNY USA', embed: 'https://dlhd.dad/stream/stream-768.php', category: 'News', channelNumber: 341 },
  { name: 'Fox Weather Channel', embed: 'https://dlhd.dad/stream/stream-775.php', category: 'News', channelNumber: 342 },
  { name: 'GOL PLAY Spain', embed: 'https://dlhd.dad/stream/stream-530.php', category: 'Sports', channelNumber: 343 },
  { name: 'GOLF Channel USA', embed: 'https://dlhd.dad/stream/stream-318.php', category: 'Sports', channelNumber: 344 },
  { name: 'Game Show Network', embed: 'https://dlhd.dad/stream/stream-319.php', category: 'Entertainment', channelNumber: 345 },
  { name: 'Gold UK', embed: 'https://dlhd.dad/stream/stream-687.php', category: 'Entertainment', channelNumber: 346 },
  { name: 'Grit Channel', embed: 'https://dlhd.dad/stream/stream-752.php', category: 'Entertainment', channelNumber: 347 },
  { name: 'Global CA', embed: 'https://dlhd.dad/stream/stream-836.php', category: 'Entertainment', channelNumber: 348 },
  { name: 'The Hallmark Channel', embed: 'https://dlhd.dad/stream/stream-320.php', category: 'Entertainment', channelNumber: 349 },
  { name: 'HBO USA', embed: 'https://dlhd.dad/stream/stream-321.php', category: 'Movies', channelNumber: 350 },
  { name: 'HBO2 USA', embed: 'https://dlhd.dad/stream/stream-689.php', category: 'Movies', channelNumber: 351 },
  { name: 'HGTV', embed: 'https://dlhd.dad/stream/stream-382.php', category: 'Lifestyle', channelNumber: 352 },
  { name: 'History USA', embed: 'https://dlhd.dad/stream/stream-322.php', category: 'Documentary', channelNumber: 353 },
  { name: 'ITV 1 UK', embed: 'https://dlhd.dad/stream/stream-350.php', category: 'Entertainment', channelNumber: 354 },
  { name: 'ITV 2 UK', embed: 'https://dlhd.dad/stream/stream-351.php', category: 'Entertainment', channelNumber: 355 },
  { name: 'ITV 3 UK', embed: 'https://dlhd.dad/stream/stream-352.php', category: 'Entertainment', channelNumber: 356 },
  { name: 'ITV 4 UK', embed: 'https://dlhd.dad/stream/stream-353.php', category: 'Entertainment', channelNumber: 357 },
  { name: 'Investigation Discovery (ID USA)', embed: 'https://dlhd.dad/stream/stream-324.php', category: 'Documentary', channelNumber: 358 },
  { name: 'ION USA', embed: 'https://dlhd.dad/stream/stream-325.php', category: 'Entertainment', channelNumber: 359 },
  { name: 'IFC TV USA', embed: 'https://dlhd.dad/stream/stream-656.php', category: 'Movies', channelNumber: 360 },
  { name: 'LaLigaTV UK', embed: 'https://dlhd.dad/stream/stream-276.php', category: 'Sports', channelNumber: 361 },
  { name: 'Law & Crime Network', embed: 'https://dlhd.dad/stream/stream-278.php', category: 'News', channelNumber: 362 },
  { name: 'Lifetime Network', embed: 'https://dlhd.dad/stream/stream-326.php', category: 'Entertainment', channelNumber: 363 },
  { name: 'MSNBC', embed: 'https://dlhd.dad/stream/stream-327.php', category: 'News', channelNumber: 364 },
  { name: 'MTV UK', embed: 'https://dlhd.dad/stream/stream-367.php', category: 'Entertainment', channelNumber: 365 },
  { name: 'MTV USA', embed: 'https://dlhd.dad/stream/stream-371.php', category: 'Entertainment', channelNumber: 366 },
  { name: 'MUTV UK', embed: 'https://dlhd.dad/stream/stream-377.php', category: 'Sports', channelNumber: 367 },
  { name: 'MLB Network USA', embed: 'https://dlhd.dad/stream/stream-399.php', category: 'Sports', channelNumber: 368 },
  { name: 'NHL Network USA', embed: 'https://dlhd.dad/stream/stream-663.php', category: 'Sports', channelNumber: 369 },
  { name: 'NFL RedZone', embed: 'https://dlhd.dad/stream/stream-667.php', category: 'Sports', channelNumber: 370 },
  { name: 'NBC USA', embed: 'https://dlhd.dad/stream/stream-53.php', category: 'Entertainment', channelNumber: 371 },
  { name: 'NBA TV USA', embed: 'https://dlhd.dad/stream/stream-404.php', category: 'Sports', channelNumber: 372 },
  { name: 'National Geographic (NGC)', embed: 'https://dlhd.dad/stream/stream-328.php', category: 'Documentary', channelNumber: 373 },
  { name: 'NICK JR', embed: 'https://dlhd.dad/stream/stream-329.php', category: 'Kids', channelNumber: 374 },
  { name: 'NICK', embed: 'https://dlhd.dad/stream/stream-330.php', category: 'Kids', channelNumber: 375 },
  { name: 'Nicktoons', embed: 'https://dlhd.dad/stream/stream-649.php', category: 'Kids', channelNumber: 376 },
  { name: 'NBC Universo', embed: 'https://dlhd.dad/stream/stream-845.php', category: 'Entertainment', channelNumber: 377 },
  { name: 'Oxygen True Crime', embed: 'https://dlhd.dad/stream/stream-332.php', category: 'Documentary', channelNumber: 378 },
  { name: 'Paramount Network', embed: 'https://dlhd.dad/stream/stream-334.php', category: 'Entertainment', channelNumber: 379 },
  { name: 'Sky Sports Premier League', embed: 'https://dlhd.dad/stream/stream-130.php', category: 'Sports', channelNumber: 380 },
  { name: 'Sky Sports Cricket', embed: 'https://dlhd.dad/stream/stream-65.php', category: 'Sports', channelNumber: 381 },
  { name: 'Sky Sports Golf UK', embed: 'https://dlhd.dad/stream/stream-70.php', category: 'Sports', channelNumber: 382 },
  { name: 'Sky Sports News UK', embed: 'https://dlhd.dad/stream/stream-366.php', category: 'News', channelNumber: 383 },
  { name: 'Sport TV1 Portugal', embed: 'https://dlhd.dad/stream/stream-49.php', category: 'Sports', channelNumber: 384 },
  { name: 'Sport TV2 Portugal', embed: 'https://dlhd.dad/stream/stream-74.php', category: 'Sports', channelNumber: 385 },
  { name: 'SSC Sport 1', embed: 'https://dlhd.dad/stream/stream-614.php', category: 'Sports', channelNumber: 386 },
  { name: 'Showtime USA', embed: 'https://dlhd.dad/stream/stream-333.php', category: 'Movies', channelNumber: 387 },
  { name: 'Starz', embed: 'https://dlhd.dad/stream/stream-335.php', category: 'Movies', channelNumber: 388 },
  { name: 'SYFY USA', embed: 'https://dlhd.dad/stream/stream-373.php', category: 'Entertainment', channelNumber: 389 },
  { name: 'TNT Sports 1 UK', embed: 'https://dlhd.dad/stream/stream-31.php', category: 'Sports', channelNumber: 390 },
  { name: 'TNT Sports 2 UK', embed: 'https://dlhd.dad/stream/stream-32.php', category: 'Sports', channelNumber: 391 },
  { name: 'TNT Sports 3 UK', embed: 'https://dlhd.dad/stream/stream-33.php', category: 'Sports', channelNumber: 392 },
  { name: 'TNT Sports 4 UK', embed: 'https://dlhd.dad/stream/stream-34.php', category: 'Sports', channelNumber: 393 },
  { name: 'TBS USA', embed: 'https://dlhd.dad/stream/stream-336.php', category: 'Entertainment', channelNumber: 394 },
  { name: 'TLC', embed: 'https://dlhd.dad/stream/stream-337.php', category: 'Lifestyle', channelNumber: 395 },
  { name: 'TNT USA', embed: 'https://dlhd.dad/stream/stream-338.php', category: 'Entertainment', channelNumber: 396 },
  { name: 'Telemundo', embed: 'https://dlhd.dad/stream/stream-131.php', category: 'Entertainment', channelNumber: 397 },
  { name: 'TruTV USA', embed: 'https://dlhd.dad/stream/stream-341.php', category: 'Entertainment', channelNumber: 398 },
  { name: 'USA Network', embed: 'https://dlhd.dad/stream/stream-343.php', category: 'Entertainment', channelNumber: 399 },
  { name: 'Univision', embed: 'https://dlhd.dad/stream/stream-132.php', category: 'Entertainment', channelNumber: 400 },
  { name: 'VH1 USA', embed: 'https://dlhd.dad/stream/stream-344.php', category: 'Entertainment', channelNumber: 401 },
  { name: 'Willow Cricket', embed: 'https://dlhd.dad/stream/stream-346.php', category: 'Sports', channelNumber: 402 },
  { name: 'WWE Network', embed: 'https://dlhd.dad/stream/stream-376.php', category: 'Sports', channelNumber: 403 },
  { name: 'Ziggo Sport NL', embed: 'https://dlhd.dad/stream/stream-393.php', category: 'Sports', channelNumber: 404 },
  { name: 'Food Network', embed: 'https://dlhd.dad/stream/stream-384.php', category: 'Lifestyle', channelNumber: 405 }
];

export const CHANNEL_DESCRIPTIONS: Record<string, string> = {
  'ABC USA': 'American news and entertainment programming.',
  'AHC (American Heroes Channel)': 'History and stories of military and pioneering heroes.',
  'Antenna TV USA': 'Classic television shows and sitcoms.',
  'A&E USA': 'High-quality reality series and investigative documentaries.',
  'AMC USA': 'Award-winning original series and movies.',
  'Animal Planet': 'Wildlife documentaries and animal-focused entertainment.',
  'Astro SuperSport 1': 'Regional sports coverage from Malaysia.',
  'Astro SuperSport 2': 'International sports events and regional highlights.',
  'Astro SuperSport 3': 'Football, motorsports, and more from Astro.',
  'Astro SuperSport 4': 'Additional sports programming and niche events.',
  'Arena Sport 1 Premium': 'Premium European sports coverage.',
  'Arena Sport 2 Premium': 'Live football and basketball from Europe.',
  'Arena Sport 3 Premium': 'Top-tier international sports matches.',
  'Arena Sport 1 Serbia': 'Serbian sports broadcasting leader.',
  'Arena Sport 2 Serbia': 'Regional Balkan sports coverage.',
  'Arena Sport 3 Serbia': 'Football and basketball from Serbia.',
  'Arena Sport 4 Serbia': 'Live action and sports news from the region.',
  'Arena Sport 1 Croatia': 'Croatian language sports broadcasting.',
  'Arena Sport 2 Croatia': 'Sports events tailored for Croatian viewers.',
  'Arena Sport 3 Croatia': 'Live Croatian league and international matches.',
  'Arena Sport 4 Croatia': 'Additional Croatian sports programming.',
  'Alkass One': 'Middle Eastern sports focus, primarily football.',
  'Alkass Two': 'Regional GCC sports and local tournaments.',
  'Alkass Three': 'Live coverage of Middle Eastern athletics.',
  'Alkass Four': 'Additional Alkass event coverage.',
  'Arena Sport 1 BiH': 'Sports coverage for Bosnia and Herzegovina.',
  'Abu Dhabi Sports 1 UAE': 'Leading sports network from the UAE.',
  'Abu Dhabi Sports 2 UAE': 'Focus on local and regional Arab sports.',
  'Abu Dhabi Sports 1 Premium': 'Premium UAE sports and international events.',
  'Abu Dhabi Sports 2 Premium': 'Exclusive UAE sports broadcasting.',
  'Astro Cricket': '24/7 coverage of international cricket.',
  'Antena 3 Spain': 'Spanish news and entertainment.',
  'Arena Sports Tenis Serbia': 'Dedicated tennis coverage from Serbia.',
  'ACC Network USA': 'College sports from the Atlantic Coast Conference.',
  'Adult Swim': 'Animation and live-action for adult audiences.',
  'A Sport PK': 'Sports channel from Pakistan.',
  'AXN Movies Portugal': 'Feature films and series in Portugal.',
  'Arte DE': 'European culture and arts channel (German).',
  'AXS TV USA': 'Music, entertainment, and lifestyle network.',
  'ABC NY USA': 'Local New York news and ABC programming.',
  'Azteca 7 MX': 'Mexican entertainment and sports.',
  'Altitude Sports': 'Regional sports network for the Rocky Mountain area.',
  'Azteca Uno MX': 'Primary Mexican general entertainment.',
  'Arena Sport 5 Serbia': 'Expansion sports channel for Serbian viewers.',
  'Arena Sport 6 Serbia': 'Live football and basketball expansion.',
  'Arena Sport 7 Serbia': 'Additional regional sports events.',
  'Arena Sport 8 Serbia': 'Expansion for Balkan sports coverage.',
  'Arena Sport 9 Serbia': 'Live action and niche sports.',
  'Arena Sport 10 Serbia': 'Comprehensive Serbian sports coverage.',
  'Arte France': 'Culture and arts programming from France.',
  'Automoto La chaîne': 'Dedicated to cars and motorsports.',
  'ATV Turkey': 'Turkish entertainment and news channel.',
  'A Spor Turkey': 'Sports news and events from Turkey.',
  'beIN Sports MENA English 1': 'English language sports from beIN MENA.',
  'beIN Sports MENA English 2': 'Additional English sports programming.',
  'beIN Sports 1 Arabic': 'Primary Arabic sports coverage.',
  'beIN Sports 2 Arabic': 'Live football focus (Arabic).',
  'beIN Sports 3 Arabic': 'International events in Arabic.',
  'beIN Sports 4 Arabic': 'Middle Eastern sports highlights.',
  'beIN Sports 5 Arabic': 'Regional tournament coverage.',
  'beIN Sports 6 Arabic': 'Live athletics and basketball.',
  'beIN Sports 7 Arabic': 'Global soccer in Arabic.',
  'beIN Sports 8 Arabic': 'Niche sports and live action.',
  'beIN Sports 9 Arabic': 'Comprehensive beIN coverage.',
  'beIN SPORTS XTRA 1': 'Free-to-air sports and highlights.',
  'beIN Sports MAX 4 France': 'French language sports expansion.',
  'beIN Sports MAX 5 France': 'Live football expansion for France.',
  'beIN Sports MAX 6 France': 'Additional sports for French viewers.',
  'beIN Sports MAX 7 France': 'Niche sports events in France.',
  'beIN Sports MAX 8 France': 'Sports coverage expansion.',
  'beIN Sports MAX 9 France': 'Live action for beIN France.',
  'beIN Sports MAX 10 France': 'Comprehensive French sports coverage.',
  'beIN SPORTS 1 France': 'Primary French beIN sports channel.',
  'beIN SPORTS 2 France': 'Live soccer focus for France.',
  'beIN SPORTS 3 France': 'International sports for France.',
  'beIN SPORTS 1 Turkey': 'Leading sports channel in Turkey.',
  'beIN SPORTS 2 Turkey': 'Turkish football focus.',
  'beIN SPORTS 3 Turkey': 'Basketball and local sports (Turkey).',
  'beIN SPORTS 4 Turkey': 'Additional Turkish sports events.',
  'BeIN Sports HD Qatar': 'High definition sports from Qatar.',
  'BeIN SPORTS USA': 'American branch of the global beIN network.',
  'beIN SPORTS en Español': 'Spanish language sports for the US.',
  'beIN SPORTS Australia 1': 'Australian beIN sports coverage.',
  'beIN SPORTS Australia 2': 'Soccer and tennis focus for Australia.',
  'beIN SPORTS Australia 3': 'Additional Australian sports action.',
  'Barca TV Spain': 'The official channel of FC Barcelona.',
  'Benfica TV PT': 'The official channel of SL Benfica.',
  'Boomerang': 'Classic and retro cartoons.',
  'BNT 1 Bulgaria': 'Bulgarian national television.',
  'BNT 2 Bulgaria': 'Regional Bulgarian programming.',
  'BNT 3 Bulgaria': 'Sports and entertainment from Bulgaria.',
  'BR Fernsehen DE': 'Bavarian public broadcasting.',
  'bTV Bulgaria': 'Private Bulgarian entertainment.',
  'bTV Action Bulgaria': 'Movies and sports for Bulgaria.',
  'bTV Lady Bulgaria': 'Lifestyle and dramas for women.',
  'BBC America (BBCA)': 'British series and nature documentaries for the US.',
  'BET USA': 'Black Entertainment Television.',
  'Bravo USA': 'Reality TV and pop culture.',
  'BBC News Channel HD': '24/7 global news from London.',
  'BBC One UK': 'Primary UK entertainment channel.',
  'BBC Two UK': 'Cerebral and alternative UK programming.',
  'BBC Three UK': 'Youth-focused UK entertainment.',
  'BBC Four UK': 'Arts and science documentaries from the UK.',
  'BIG TEN Network (BTN USA)': 'College sports from the Big Ten conference.',
  'beIN Sports 1 Malaysia': 'Malaysian beIN sports branch.',
  'beIN Sports 2 Malaysia': 'Additional sports for Malaysia.',
  'beIN Sports 3 Malaysia': 'Football focus for Malaysia.',
  'BFM TV France': '24/7 news from France.',
  'bein Sports 5 Turkey': 'Turkish sports expansion.',
  'Bandsports Brasil': 'Brazilian sports and motorsports.',
  'Canal+ MotoGP France': 'Dedicated MotoGP coverage (French).',
  'Canal+ Formula 1': 'Dedicated F1 coverage (French).',
  'CW PIX 11 USA': 'New York CW affiliate.',
  'CBS USA': 'Major American network programming.',
  'Court TV USA': 'Legal news and live trial coverage.',
  'CW USA': 'Youth-oriented dramas and reality.',
  'CNBC USA': 'Business and financial news.',
  'Comedy Central': 'Stand-up and comedic series.',
  'Cartoon Network': 'Animated programming for all ages.',
  'CNN USA': 'Global breaking news network.',
  'Cinemax USA': 'Premium movies and action series.',
  'Cuatro Spain': 'Spanish general entertainment.',
  'Channel 4 UK': 'British public-service broadcaster.',
  'Channel 5 UK': 'UK-based entertainment and documentaries.',
  'CBS Sports Network (CBSSN)': 'American sports and college athletics.',
  'Canal+ France': 'Premium French movies and sports.',
  'Canal+ Sport France': 'Elite sports coverage from France.',
  'Canal+ Foot France': 'Dedicated football channel (French).',
  'Canal+ Sport360': 'Multi-sport coverage from Canal+.',
  'Canal 11 Portugal': 'Portuguese football federation channel.',
  'Canal+ Sport Poland': 'Polish sports broadcasting leader.',
  'Canal+ Sport 2 Poland': 'Additional sports for Poland.',
  'Canal+ Sport 3 Poland': 'Ekstraklasa focus for Poland.',
  'Canal+ Sport 5 Poland': 'Polish sports and news.',
  'Canal+ Premium Poland': 'Premium movies and series (Poland).',
  'Canal+ Family Poland': 'Family-friendly movies and series.',
  'Canal+ Seriale Poland': 'Non-stop TV series (Poland).',
  'Canal+ Sport 1 Afrique': 'African sports coverage from Canal+.',
  'Canal+ Sport 2 Afrique': 'Additional sports for Africa.',
  'Canal+ Sport 3 Afrique': 'Soccer focus for Africa.',
  'Canal+ Sport 4 Afrique': 'Events and highlights for Africa.',
  'Canal+ Sport 5 Afrique': 'Comprehensive African sports.',
  'CANAL 9 Denmark': 'Danish sports and entertainment.',
  'Combate Brasil': 'Mixed Martial Arts focus from Brazil.',
  'Cosmote Sport 1 HD': 'Leading Greek sports network.',
  'Cosmote Sport 2 HD': 'Greek football focus.',
  'Cosmote Sport 3 HD': 'International soccer in Greece.',
  'Cosmote Sport 4 HD': 'Basketball and ATP tennis (Greece).',
  'Cosmote Sport 5 HD': 'Motorsports focus (Greece).',
  'Cosmote Sport 6 HD': 'Tennis and athletics (Greece).',
  'Cosmote Sport 7 HD': 'Live sports expansion for Greece.',
  'Cosmote Sport 8 HD': 'Greek sports news and events.',
  'Cosmote Sport 9 HD': 'Additional Greek sports coverage.',
  'Channel 9 Israel': 'Russian-language Israeli channel.',
  'Channel 10 Israel': 'Israeli commercial entertainment.',
  'Channel 11 Israel': 'Public Israeli broadcasting.',
  'Channel 12 Israel': 'Keshet 12 entertainment and news.',
  'Channel 13 Israel': 'Reshet 13 entertainment.',
  'Channel 14 Israel': 'News and commentary from Israel.',
  'C More First Sweden': 'Premium movie premieres in Sweden.',
  'C More Hits Sweden': 'Popular films and blockbusters.',
  'C More Series Sweden': 'International and local TV series.',
  'COZI TV USA': 'Classic television network.',
  'CMT USA': 'Country Music Television.',
  'CTV Canada': 'Largest Canadian private broadcaster.',
  'CTV 2 Canada': 'Secondary Canadian entertainment network.',
  'Crime+ Investigation USA': 'True crime and criminal justice.',
  'Comet USA': 'Science fiction and supernatural series.',
  'Cooking Channel USA': 'Culinary travel and lifestyle.',
  'Cleo TV': 'Lifestyle for women of color.',
  'C SPAN 1': 'Public affairs and government proceedings.',
  'CBSNY USA': 'Local New York CBS news.',
  'Chicago Sports Network': 'Regional Chicago sports coverage.',
  'Citytv': 'Canadian urban-themed entertainment.',
  'CBC CA': 'Canadian public broadcaster.',
  'Claro Sports MX': 'Mexican sports network.',
  'Canal5 MX': 'Youth-focused Mexican entertainment.',
  'C8 France': 'French general interest channel.',
  'CNews France': 'French language news channel.',
  'Canal+ Sport CZ': 'Sports channel for Czech/Slovak viewers.',
  'CT Sport CZ': 'Czech public sports channel.',
  'Nova HD CZ': 'Primary Czech commercial channel.',
  'CT1 HD CZ': 'First Czech public channel.',
  'CT2 HD CZ': 'Alternative Czech public programming.',
  'TN Live CZ': 'Czech 24-hour news.',
  'OnePlay Sport 4 CZ': 'Czech sports expansion.',
  'OnePlay MD2 CZ': 'Sports event coverage (Czech).',
  'OnePlay MD3 CZ': 'Additional event streaming.',
  'OnePlay MD4 CZ': 'Czech sports live coverage.',
  'Sport 1 CZ': 'Central European sports channel.',
  'Canal+ Sport 2 CZ': 'Premier League focus for CZ.',
  'Canal+ Sport 3 CZ': 'Live sports expansion.',
  'Canal+ Sport 4 CZ': 'Sports news and action.',
  'Canal+ Sport 5 CZ': 'Additional CZ sports coverage.',
  'Canal+ Sport 6 CZ': 'International sports events.',
  'Canal+ Sport 7 CZ': 'Czech/Slovak sports expansion.',
  'Canal+ Sport 8 CZ': 'Comprehensive sports for CZ.',
  'JOJ SK': 'Slovak commercial television.',
  'Dajto SK': 'Male-oriented Slovak channel.',
  'JOJ Šport SK': 'Slovak dedicated sports channel.',
  'Voyo Special 1 SK': 'Slovak streaming special events.',
  'Voyo Special 2 SK': 'Additional Voyo live streams.',
  'Voyo Special 3 SK': 'Exclusive Slovak digital content.',
  'Voyo Special 4 SK': 'Voyo live event expansion.',
  'Voyo Special 7 SK': 'Streaming sports and action.',
  'Voyo Special 8 SK': 'Digital Slovak entertainment.',
  'Voyo Special 9 SK': 'Specialized live events.',
  'Nova Sport 3 SK': 'Slovak premium sports channel.',
  'Nova Sport 4 SK': 'Live football and basketball (Slovak).',
  'Nova Sport 5 SK': 'Motorsports focus for Slovakia.',
  'Canal+ Sport SK': 'Premier League focus for SK.',
  'Canal+ Sport 2 SK': 'Live soccer for Slovak viewers.',
  'Canal+ Sport 3 SK': 'Additional Slovak sports events.',
  'Canal+ Sport 4 SK': 'Comprehensive SK sports coverage.',
  'CBS Sports Golazo': '24/7 soccer news and action.',
  'CMTV Portugal': 'Portuguese news and sensationalist media.',
  'Cytavision Sports 1 Cyprus': 'Premier Cypriot sports network.',
  'Cytavision Sports 2 Cyprus': 'Football focus for Cyprus.',
  'Cytavision Sports 3 Cyprus': 'Basketball and local events.',
  'Cytavision Sports 4 Cyprus': 'International soccer in Cyprus.',
  'Cytavision Sports 5 Cyprus': 'Motorsports and tennis.',
  'Cytavision Sports 6 Cyprus': 'Live action for Cyprus.',
  'Cytavision Sports 7 Cyprus': 'Comprehensive Cypriot sports.',
  'DAZN 1 UK': 'Global sports streaming channel.',
  'Discovery Velocity CA': 'High-stakes Canadian lifestyle.',
  'DAZN 1 Bar DE': 'German sports for public venues.',
  'DAZN 2 Bar DE': 'Additional sports for German bars.',
  'DAZN 1 Spain': 'Premier sports streaming in Spain.',
  'DAZN 2 Spain': 'Motorsports and football (Spain).',
  'DAZN 3 Spain': 'International sports for Spain.',
  'DAZN 4 Spain': 'Live action expansion (Spain).',
  'DAZN F1 ES': 'Dedicated Formula 1 in Spanish.',
  'DAZN LaLiga': 'La Liga focus for Spain.',
  'DAZN Portugal FIFA Mundial de Clubes': 'Portuguese club world cup coverage.',
  'DR1 Denmark': 'Danish national public channel.',
  'DR2 Denmark': 'Danish culture and news.',
  'DAZN Ligue 1 France': 'Ligue 1 focus for France.',
  'Digi Sport 1 Romania': 'Leading Romanian sports network.',
  'Digi Sport 2 Romania': 'Romanian football focus.',
  'Digi Sport 3 Romania': 'International events (Romania).',
  'Digi Sport 4 Romania': 'Local sports and news.',
  'Diema Sport Bulgaria': 'Bulgarian premium sports.',
  'Diema Sport 2 Bulgaria': 'English football focus (Bulgaria).',
  'Diema Sport 3 Bulgaria': 'Live sports expansion.',
  'Diema Bulgaria': 'General entertainment for Bulgaria.',
  'Diema Family Bulgaria': 'Dramas and family series.',
  'Dubai Sports 1 UAE': 'Public sports broadcaster from Dubai.',
  'Dubai Sports 2 UAE': 'Arab world sports focus.',
  'Dubai Sports 3 UAE': 'Additional Dubai sports programming.',
  'Dubai Racing 2 UAE': 'Horse racing focus (UAE).',
  'DSTV Mzansi Magic': 'South African general entertainment.',
  'DSTV M-Net': 'Premium South African movies/series.',
  'DSTV kykNET & kie': 'Afrikaans language entertainment.',
  'DAZN ZONA Italy': 'Italian sports streaming channel.',
  'Discovery Life Channel': 'Health and fitness documentaries.',
  'Disney Channel': 'Family-friendly Disney series.',
  'Discovery Channel': 'Science and nature documentaries.',
  'Discovery Family': 'Education and family programming.',
  'Disney XD': 'Action and adventure animation.',
  'Destination America': 'American travel and food.',
  'Disney JR': 'Preschool programming.',
  'Dave': 'British comedy-focused channel.',
  'ESPN USA': 'The leader in sports news and games.',
  'ESPN2 USA': 'Live sports and original programming.',
  'ESPNU USA': 'College sports focus.',
  'ESPN 1 NL': 'Dutch sports broadcasting.',
  'ESPN 2 NL': 'International events for NL.',
  'Eleven Sports 1 Poland': 'Elite sports for Polish viewers.',
  'Eleven Sports 2 Poland': 'Motorsports and football (Poland).',
  'Eleven Sports 3 Poland': 'Live European soccer.',
  'Eleven Sports 1 Portugal': 'Portuguese premium sports.',
  'Eleven Sports 2 Portugal': 'International soccer focus.',
  'Eleven Sports 3 Portugal': 'Tennis and basketball.',
  'Eleven Sports 4 Portugal': 'Additional event expansion.',
  'Eleven Sports 5 Portugal': 'Live action for Portugal.',
  'EuroSport 1 Greece': 'European sports focus (Greece).',
  'EuroSport 2 Greece': 'Alternative sports for Greece.',
  'EuroSport 1 Poland': 'Olympic and niche sports (Poland).',
  'EuroSport 2 Poland': 'European sports expansion.',
  'Eurosport 1 SW': 'Swedish Eurosport coverage.',
  'Eurosport 2 SW': 'Expansion for Sweden.',
  'Eurosport 1 NL': 'Dutch Eurosport coverage.',
  'Eurosport 2 NL': 'Expansion for the Netherlands.',
  'EuroSport 1 Spain': 'Primary Eurosport for Spain.',
  'EuroSport 2 Spain': 'Additional Spanish sports coverage.',
  'EuroSport 1 Italy': 'Italian Eurosport coverage.',
  'EuroSport 2 Italy': 'Expansion for Italy.',
  'ESPN Premium Argentina': 'Premium soccer from Argentina.',
  'ESPN Brasil': 'Primary Brazilian ESPN channel.',
  'ESPN2 Brasil': 'International sports for Brazil.',
  'ESPN3 Brasil': 'US sports focus for Brazil.',
  'ESPN4 Brasil': 'Live action expansion.',
  'ESPN Argentina': 'Leading sports network in Argentina.',
  'ESPN2 Argentina': 'Live football focus (Argentina).',
  'ESPN Deportes': 'Spanish-language sports for the US.',
  'ESPNews': '24/7 sports news and analysis.',
  'E! Entertainment Television': 'Pop culture and celebrity news.',
  'E4 Channel': 'UK youth-focused entertainment.',
  'ESPN 3 NL': 'Dutch sports expansion.',
  'ERT 1 Greece': 'Greek national broadcasting.',
  'Eurosport 1 France': 'French Eurosport coverage.',
  'Eurosport 2 France': 'Expansion for France.',
  'ESPN3 Argentina': 'Additional Argentine sports events.',
  'ESPN 1 MX': 'Leading sports in Mexico.',
  'ESPN 2 MX': 'Mexican sports focus.',
  'ESPN 3 MX': 'International sports for Mexico.',
  'ESPN 4 MX': 'Additional Mexican sports coverage.',
  'FUSE TV USA': 'Music and youth culture.',
  'Fox Sports 1 USA': 'National sports coverage (US).',
  'Fox Sports 2 USA': 'Extreme sports and live events.',
  'FOX Soccer Plus': 'International soccer and rugby.',
  'Fox Cricket': 'Dedicated Australian cricket channel.',
  'FOX Deportes USA': 'Spanish language US sports.',
  'FOX Sports 502 AU': 'Australian sports expansion.',
  'FOX Sports 503 AU': 'Cricket and soccer (AU).',
  'FOX Sports 504 AU': 'Rugby focus (Australia).',
  'FOX Sports 505 AU': 'Live action for Australia.',
  'FOX Sports 506 AU': 'Motorsports focus (AU).',
  'FOX Sports 507 AU': 'Comprehensive Australian sports.',
  'Fox Sports 1 MX': 'Primary Mexican Fox sports channel.',
  'Fox Sports 2 MX': 'Live soccer focus for Mexico.',
  'Fox Sports 3 MX': 'Motorsports for Mexico.',
  'Fox Sports Argentina': 'Leading sports in Argentina.',
  'Fox Sports 2 Argentina': 'Balkan and local sports focus.',
  'Fox Sports 3 Argentina': 'Additional Argentine action.',
  'Fox Sports Premium MX': 'Premium Mexican sports coverage.',
  'FilmBox Premium Poland': 'High-end cinema for Poland.',
  'Fight Network': 'Combat sports and MMA.',
  'Fox Business': 'Financial news and market updates.',
  'FOX HD Bulgaria': 'Bulgarian version of Fox.',
  'FOX USA': 'Primary Fox entertainment network.',
  'FX USA': 'Critically acclaimed dramas and movies.',
  'FXX USA': 'Comedy focus and experimental series.',
  'Freeform': 'Young adult series and movies.',
  'Fox News': '24/7 American news coverage.',
  'FX Movie Channel': 'Feature films and classic FX content.',
  'FYI': 'Inspirational lifestyle programming.',
  'Film4 UK': 'Free-to-air British movies.',
  'Fashion TV': 'Global fashion and trends.',
  'FETV - Family Entertainment Television': 'Wholesome family programming.',
  'FOXNY USA': 'Local New York Fox news.',
  'Fox Weather Channel': 'Meteorology and climate news.',
  'GOL PLAY Spain': 'Spanish sports and news.',
  'GOLF Channel USA': '24/7 golf coverage.',
  'Game Show Network': 'Competitive games and trivia.',
  'Gold UK': 'Classic British comedy.',
  'Grit Channel': 'Westerns and action movies.',
  'Global CA': 'Canadian national entertainment.',
  'The Hallmark Channel': 'Heartfelt movies and dramas.',
  'HBO USA': 'Premium movies and original series.',
  'HBO2 USA': 'Secondary premium HBO channel.',
  'HGTV': 'Home and garden improvement.',
  'History USA': 'Historical documentaries and series.',
  'ITV 1 UK': 'Leading British commercial channel.',
  'ITV 2 UK': 'Youth and reality TV (UK).',
  'ITV 3 UK': 'Classic British dramas.',
  'ITV 4 UK': 'Sports and action for UK viewers.',
  'Investigation Discovery (ID USA)': 'True crime and investigations.',
  'ION USA': 'Procedural dramas and series.',
  'IFC TV USA': 'Independent film and cult comedy.',
  'LaLigaTV UK': 'English language La Liga focus.',
  'Law & Crime Network': 'Legal trials and crime news.',
  'Lifetime Network': 'Movies and series for women.',
  'MSNBC': 'Political analysis and news.',
  'MTV UK': 'UK music and reality TV.',
  'MTV USA': 'American youth culture and music.',
  'MUTV UK': 'Official Manchester United channel.',
  'MLB Network USA': 'Major League Baseball coverage.',
  'NHL Network USA': 'National Hockey League news and games.',
  'NFL RedZone': 'Commercial-free NFL Sunday coverage.',
  'NBC USA': 'American network news and entertainment.',
  'NBA TV USA': 'Professional basketball news and action.',
  'National Geographic (NGC)': 'World-class science and nature.',
  'NICK JR': 'Educational preschool shows.',
  'NICK': 'Kids and teen entertainment.',
  'Nicktoons': '24/7 animated series.',
  'NBC Universo': 'Spanish language entertainment for the US.',
  'Oxygen True Crime': 'Women-focused crime documentaries.',
  'Paramount Network': 'Drama series and movies.',
  'Sky Sports Premier League': 'Premier football from the UK.',
  'Sky Sports Cricket': 'Dedicated cricket action.',
  'Sky Sports Golf UK': 'The home of professional golf.',
  'Sky Sports News UK': 'Sports news from around the world.',
  'Sport TV1 Portugal': 'Elite Portuguese sports.',
  'Sport TV2 Portugal': 'International soccer focus (PT).',
  'SSC Sport 1': 'Saudi Arabian sports leader.',
  'Showtime USA': 'Premium movies and boxing.',
  'Starz': 'Blockbuster films and original dramas.',
  'SYFY USA': 'Science fiction and fantasy.',
  'TNT Sports 1 UK': 'Live European sports for the UK.',
  'TNT Sports 2 UK': 'Additional UK sports coverage.',
  'TNT Sports 3 UK': 'Elite international events.',
  'TNT Sports 4 UK': 'Comprehensive TNT sports.',
  'TBS USA': 'Comedy and sports focus.',
  'TLC': 'Personal stories and reality TV.',
  'TNT USA': 'Drama, movies, and sports.',
  'Telemundo': 'Spanish language dramas and news.',
  'TruTV USA': 'Humorous reality and legal shows.',
  'USA Network': 'Entertainment and live sports.',
  'Univision': 'Largest Spanish network in the US.',
  'VH1 USA': 'Music-related reality and entertainment.',
  'Willow Cricket': 'Cricket coverage for the US.',
  'WWE Network': 'Wrestling and sports entertainment.',
  'Ziggo Sport NL': 'Dutch sports broadcasting.',
  'Food Network': 'Cooking and food culture.'
};
