import { LiveChannel } from '../types';

export const LIVE_CHANNELS: LiveChannel[] = [
  { name: 'Cartoon Network', embed: 'https://dlhd.dad/stream/stream-339.php', category: 'Kids', channelNumber: 1 },
  { name: 'NICK', embed: 'https://dlhd.dad/stream/stream-330.php', category: 'Kids', channelNumber: 2 },
  { name: 'Nicktoons', embed: 'https://dlhd.dad/stream/stream-649.php', category: 'Kids', channelNumber: 3 },
  { name: 'Disney Channel', embed: 'https://dlhd.dad/stream/stream-312.php', category: 'Kids', channelNumber: 4 },
  { name: 'Disney XD', embed: 'https://dlhd.dad/stream/stream-314.php', category: 'Kids', channelNumber: 5 },
  { name: 'Disney JR', embed: 'https://dlhd.dad/stream/stream-652.php', category: 'Kids', channelNumber: 6 },
  { name: 'Nick JR', embed: 'https://dlhd.dad/stream/stream-329.php', category: 'Kids', channelNumber: 7 },
  { name: 'Sky Sports Premier League', embed: 'https://dlhd.dad/stream/stream-130.php', category: 'Sports', channelNumber: 8 },
  { name: 'Fox Sports 1', embed: 'https://dlhd.dad/stream/stream-39.php', category: 'Sports', channelNumber: 9 },
  { name: 'Fox Sports 2', embed: 'https://dlhd.dad/stream/stream-758.php', category: 'Sports', channelNumber: 10 },
  { name: 'ESPN USA', embed: 'https://dlhd.dad/stream/stream-44.php', category: 'Sports', channelNumber: 11 },
  { name: 'NHL', embed: 'https://dlhd.dad/stream/stream-663.php', category: 'Sports', channelNumber: 12 },
  { name: 'NFL', embed: 'https://dlhd.dad/stream/stream-405.php', category: 'Sports', channelNumber: 13 },
  { name: 'NBA', embed: 'https://dlhd.dad/stream/stream-404.php', category: 'Sports', channelNumber: 14 },
  { name: 'beIN Sports', embed: 'https://dlhd.dad/stream/stream-425.php', category: 'Sports', channelNumber: 15 },
  { name: 'Sky Sports Cricket', embed: 'https://dlhd.dad/stream/stream-65.php', category: 'Sports', channelNumber: 16 },
  { name: 'WWE', embed: 'https://dlhd.dad/stream/stream-376.php', category: 'Sports', channelNumber: 17 },
  { name: 'NBC USA', embed: 'https://dlhd.dad/stream/stream-53.php', category: 'Entertainment', channelNumber: 18 },
  { name: 'FX USA', embed: 'https://dlhd.dad/stream/stream-317.php', category: 'Entertainment', channelNumber: 19 },
  { name: 'Animal Planet', embed: 'https://dlhd.dad/stream/stream-304.php', category: 'Documentary', channelNumber: 20 },
  { name: 'Fox News', embed: 'https://dlhd.dad/stream/stream-347.php', category: 'News', channelNumber: 21 },
  { name: 'CNN', embed: 'https://dlhd.dad/stream/stream-345.php', category: 'News', channelNumber: 22 },
  { name: 'ABC USA', embed: 'https://dlhd.dad/stream/stream-51.php', category: 'News', channelNumber: 23 },
  { name: 'MSNBC', embed: 'https://dlhd.dad/stream/stream-327.php', category: 'News', channelNumber: 24 },
  { name: 'CNBC', embed: 'https://dlhd.dad/stream/stream-309.php', category: 'News', channelNumber: 25 },
  { name: 'History USA', embed: 'https://dlhd.dad/stream/stream-322.php', category: 'Documentary', channelNumber: 26 },
  { name: 'Univision', embed: 'https://dlhd.dad/stream/stream-132.php', category: 'Entertainment', channelNumber: 27 },
  { name: 'HGTV', embed: 'https://dlhd.dad/stream/stream-382.php', category: 'Lifestyle', channelNumber: 28 },
  { name: 'USA Network', embed: 'https://dlhd.dad/stream/stream-343.php', category: 'Entertainment', channelNumber: 29 },
  { name: 'TLC', embed: 'https://dlhd.dad/stream/stream-337.php', category: 'Lifestyle', channelNumber: 30 },
  { name: 'TBS', embed: 'https://dlhd.dad/stream/stream-336.php', category: 'Entertainment', channelNumber: 31 },
  { name: 'CBS', embed: 'https://dlhd.dad/stream/stream-52.php', category: 'Entertainment', channelNumber: 32 },
  { name: 'Telemundo', embed: 'https://dlhd.dad/stream/stream-52.php', category: 'Entertainment', channelNumber: 33 },
  { name: 'Boomerang', embed: 'https://dlhd.dad/stream/stream-648.php', category: 'Kids', channelNumber: 34 },
  { name: 'Sky Sports 7 NZ', embed: 'https://dlhd.dad/stream/stream-594.php', category: 'Sports', channelNumber: 35 },
  { name: 'Sky Sports Premier League UK', embed: 'https://dlhd.dad/stream/stream-130.php', category: 'Sports', channelNumber: 36 },
  { name: 'CBS Sports Network USA', embed: 'https://dlhd.dad/stream/stream-308.php', category: 'Sports', channelNumber: 37 },
  { name: 'Chilevision', embed: 'https://dlhd.dad/stream/stream-77.php', category: 'Entertainment', channelNumber: 38 },
  { name: 'NBC Universo', embed: 'https://dlhd.dad/stream/stream-845.php', category: 'Entertainment', channelNumber: 39 },
  { name: 'Food Network', embed: 'https://dlhd.dad/stream/stream-384.php', category: 'Lifestyle', channelNumber: 40 }
];

export const CHANNEL_DESCRIPTIONS: Record<string, string> = {
  'Cartoon Network': 'Animated series and movies for kids featuring popular characters and original content.',
  'NICK': 'Nickelodeon - Kids entertainment with animated and live-action shows.',
  'Nicktoons': 'All cartoons, all the time! Classic and new animated series.',
  'Disney Channel': 'Family entertainment with original movies, series, and Disney favorites.',
  'Disney XD': 'Action-packed entertainment for kids with adventure shows and movies.',
  'Disney JR': 'Preschool programming and educational shows for young children.',
  'Nick JR': 'Educational programming for preschoolers.',
  'Sky Sports Premier League': 'Watch live Premier League football matches, highlights, analysis, and exclusive content.',
  'Fox Sports 1': 'Live sports coverage including NFL, MLB, college football, and more.',
  'Fox Sports 2': 'Additional sports programming and live events.',
  'ESPN USA': 'The worldwide leader in sports with live games, highlights, analysis, and sports news coverage.',
  'NHL': 'Official NHL channel featuring live hockey games, highlights, and behind-the-scenes content.',
  'NFL': 'Live NFL games, highlights, analysis, and football programming.',
  'NBA': 'Official NBA channel with live basketball games, highlights, and exclusive content.',
  'beIN Sports': 'International sports channel with soccer, tennis, motorsports, and more.',
  'Sky Sports Cricket': 'Live cricket matches, highlights, and cricket programming from around the world.',
  'WWE': 'Live WWE events, pay-per-views, original shows, and classic wrestling content.',
  'NBC USA': 'NBC network shows, news, sports, and entertainment.',
  'FX USA': 'Original dramas, comedies, and movies.',
  'Animal Planet': 'Wildlife documentaries, animal shows, and nature programming.',
  'Fox News': '24/7 news coverage and political analysis.',
  'CNN': 'Cable News Network with 24/7 news, analysis, and breaking stories.',
  'ABC USA': 'ABC network with news, entertainment, and family programming.',
  'MSNBC': 'News analysis, opinion, and live breaking news coverage.',
  'CNBC': 'Business news, market data, and financial programming.',
  'History USA': 'Historical documentaries, series, and educational programming.',
  'Univision': 'Spanish-language network with telenovelas, news, and entertainment.',
  'HGTV': 'Home and garden programming with renovation, design, and real estate shows.',
  'USA Network': 'Original series, movies, and entertainment programming.',
  'TLC': 'Reality shows and lifestyle programming featuring real-life stories.',
  'TBS': 'Comedy shows, movies, and sports programming.',
  'CBS': 'CBS network programming with news, entertainment, and sports.',
  'Telemundo': 'Spanish-language network with telenovelas, news, and entertainment.',
  'Boomerang': 'Classic cartoons and animated shows for kids.',
  'Sky Sports 7 NZ': 'New Zealand sports coverage including rugby, cricket, and more.',
  'Sky Sports Premier League UK': 'Live Premier League matches and football coverage from the UK.',
  'CBS Sports Network USA': 'American sports programming including college sports and live events.',
  'Chilevision': 'Chilean entertainment, news, and local programming.',
  'NBC Universo': 'Spanish-language sports and entertainment programming.',
  'Food Network': 'Cooking shows, competitions, and culinary entertainment.'
};
